version: "2"
linters:
  enable:
    - depguard
    - gocritic
    - misspell
    - revive
    - unconvert
    - wsl
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: Not allowed
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
            - pkg: sync/atomic
              desc: Use go.uber.org/atomic instead of sync/atomic
            - pkg: io/ioutil
              desc: Use corresponding 'os' or 'io' functions instead.
    errcheck:
      exclude-functions:
        - io.Copy
        - io.WriteString
        - (net/http.ResponseWriter).Write
        - (*net/http.Server).Shutdown
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocritic
        text: appendAssign
      - linters:
          - errcheck
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/prometheus/prometheus
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
