---
project_name: relayer_exporter
before:
  hooks:
    - go mod tidy
env:
  - CGO_ENABLED=1
builds:
  - id: relayer_exporter-linux-amd64
    main: ./cmd/relayer_exporter/relayer_exporter.go
    binary: relayer_exporter
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .CommitDate }}
      - -s -w
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs --static -lm'
    tags:
      - netgo
      - muslc

  - id: relayer_exporter-linux-arm64
    main: ./cmd/relayer_exporter/relayer_exporter.go
    binary: relayer_exporter
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .CommitDate }}
      - -s -w
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs --static -lm'
    tags:
      - netgo
      - muslc

  - id: relayer_exporter-darwin-amd64
    main: ./cmd/relayer_exporter/relayer_exporter.go
    binary: relayer_exporter
    env:
      - CC=o64-clang
      - CGO_LDFLAGS=-L/lib
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .CommitDate }}
      - -w -s
      - -linkmode=external
    tags:
      - netgo

  - id: relayer_exporter-darwin-arm64
    main: ./cmd/relayer_exporter/relayer_exporter.go
    binary: relayer_exporter
    env:
      - CC=oa64-clang
      - CGO_LDFLAGS=-L/lib
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .CommitDate }}
      - -w -s
      - -linkmode=external
    tags:
      - netgo

universal_binaries:
  - id: relayer_exporter-darwin-all
    ids:
      - relayer_exporter-darwin-amd64
      - relayer_exporter-darwin-arm64
    replace: false

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/archway-network/{{ .ProjectName }}:{{ .Version }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/archway-network/{{ .ProjectName }}:{{ .Version }}-arm64v8"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: ghcr.io/archway-network/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/archway-network/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/archway-network/{{ .ProjectName }}:{{ .Version }}-arm64v8
